parser v0.2.1-main.sha.1171107+gbad.10: handle IndexError for short literals
Included in this commit is an example that was causing this error -
see F 47-11-4. It turned out that the "1 map" literal was causing this.

Also, I observed that tee was still not capturing all output from
parse-all.sh as I reported in one of the previous commits:

fb80d0e470046c41f8bf89c00645db371ec55bc9

So I explored this issue further, and here is a solution
that I uncovered with Claude 3.5 Sonnet:

script -c './parse.sh "gbad/F/47/11/4/F 47-11-4 Notes on Elizabeth Simcoe sketches.drawio"' parse.log

This worked and saved the entire output, including the
"An unexpected error occurred" and all the traceback
added thanks to the parent commit.

I am not including parse.log to keep the repo free of noisy data;
it is enough that it has parse-all.log (regenerated here).

Here is the version of the log that I received from the the parser
prior to applying the current patch:

Script started on 2024-06-25 22:07:46-04:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="-1" LINES="-1"]
Executing command: cat "gbad/F/47/11/4/F 47-11-4 Notes on Elizabeth Simcoe sketches.drawio" | python draw_io_parser.py -m url                        -o http://gbad.archives.gov.on.ca                        -p http://gbad.archives.gov.on.ca/ > "gbad/F/47/11/4/f_47-11-4_notes_on_elizabeth_simcoe_sketches.owl"
An unexpected error occurred: IndexError: string index out of range

Traceback:
Traceback (most recent call last):
  File "/mnt/c/Users/Anonymous/records_in_contexts_draw_io_parser/draw_io_parser.py", line 1761, in _main
    _run()
  File "/mnt/c/Users/Anonymous/records_in_contexts_draw_io_parser/draw_io_parser.py", line 1756, in _run
    print(serialise(blocks, serialisation_config).rstrip())
  File "/mnt/c/Users/Anonymous/records_in_contexts_draw_io_parser/draw_io_parser.py", line 1469, in serialise
    serialised += _serialise_block(
  File "/mnt/c/Users/Anonymous/records_in_contexts_draw_io_parser/draw_io_parser.py", line 1411, in _serialise_block
    serialised_facts = list(_serialise_facts(
  File "/mnt/c/Users/Anonymous/records_in_contexts_draw_io_parser/draw_io_parser.py", line 1377, in _serialise_facts
    formatted_value = _infer_type(value)
  File "/mnt/c/Users/Anonymous/records_in_contexts_draw_io_parser/draw_io_parser.py", line 1348, in _infer_type
    elif literal[-6] == "+" or literal[-6] == "-":
IndexError: string index out of range

Manchester OWL Output saved to: gbad/F/47/11/4/f_47-11-4_notes_on_elizabeth_simcoe_sketches.owl
Executing command: ./robot.sh convert -i "gbad/F/47/11/4/f_47-11-4_notes_on_elizabeth_simcoe_sketches.owl" -o "gbad/F/47/11/4/f_47-11-4_notes_on_elizabeth_simcoe_sketches.ttl"
TTL Output saved to: gbad/F/47/11/4/f_47-11-4_notes_on_elizabeth_simcoe_sketches.ttl

Script done on 2024-06-25 22:07:51-04:00 [COMMAND_EXIT_CODE="0"]